config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  validates :content, length: { maximum: 200 }, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :delete_all
  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: true
  validates :name, presence: true

  def self.find_or_create_account(hash)
    provider = hash[:provider]
    uid = hash[:uid]
    name = hash[:info][:name]
    image = hash[:info][:image]

    User.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = name
      user.avatar = image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  private
  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ destroy ]

  # GET /posts or /posts.json
  def index
    @post = Post.new
    @posts = Post.includes(:user).page(params[:page]).per(20).order(id: "desc")
  end

  # POST /posts or /posts.json
  def create
    if logged_in?
      @post = @current_user.posts.create(post_params)
    else
      @post = Post.create(post_params)
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    redirect_to posts_url, notice: "投稿を削除しました。"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_account(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: "ログインしました。"
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "ログアウトしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show destroy ]

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_msg
      if flash[:notice]
        content_tag(:div, class: "alert alert-success") do
          flash[:notice]
        end
      end
    end

  def alert_msg
    if flash[:alert]
      content_tag(:div, class: "alert alert-danger") do
        flash[:alert]
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_name(post)
    if post.user_id
      post.user.name
    else
      "ゲストユーザー"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BulletinBoardV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg text-white">
        <div class="navbar-brand">掲示板</div>
        <div class="navbar-nav ml-auto">
          <% if logged_in? %>
            <a class="nav-item nav-link" data-toggle="modal" data-target="#modal">ログイン中のユーザー：<%= current_user.name %></a>
            <%= render "users/modal" %>
            <%= link_to("ログアウト", logout_path, method: :delete, class: "nav-item nav-link") %>
          <% else %>
            <%= link_to("ログイン", "/auth/google_oauth2", method: :post, class: "nav-item nav-link") %>
          <% end %>
        </div>
      </nav>
    </header>
    <%= notice_msg %>
    <%= alert_msg %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: false) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="my-4 d-flex align-items-end justify-content-center">
  <div class="field">
    <%= form.text_area :content, id: "post_content", style: "width: 400px; height: 100px; resize: none;"%>
  </div>
  <div class="actions ml-2">
    <%= form.submit "新規投稿" %>
  </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="py-2 px-4 bg-light border-bottom border-info" id="post_<%= post.id %>">
  <div class="row">
    <p class="col-1 m-0"><%= post.id %></p>
    <p class="col-4 m-0"><%= user_name(post) %></p>
    <p class="col-7 m-0 text-right"><%= l post.created_at %></p>
  </div>
  <hr class="my-1">
  <p class="h6"><%= post.content %></p>
  <% if current_user && current_user.id == post.user_id %>
  <%= link_to "削除", post_path(post), method: :delete, remote: true %>
  <% end %>
</div>

app/views/posts/create.js.erb
document.getElementById('posts').insertAdjacentHTML('afterbegin', '<%= j(render @post) %>');
document.getElementById('post_content').value = "";

app/views/posts/index.html.erb
<%= render "form", post: @post  %>
<hr color="#026873">
<div class="container">
  <%= paginate @posts %>
  <div id="posts" class="mb-3">
    <%= render @posts %>
  </div>
  <%= paginate @posts %>
</div>

app/views/users/_modal.html.erb
<div class="modal fade text-muted" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalSubject" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalSubject">ユーザー情報</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modalBody">
        <ul class="text-center p-0 my-3">
          <li>
            <img class="mb-3" src="<%= current_user.avatar %>">
          </li>
          <li>ユーザーID：　<%= current_user.id %></li>
          <li>ユーザー名：　<%= current_user.name %></li>
        </ul>
          <div class="modal-footer">

            <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          </div>
      </div>
    </div>
  </div>
</div>